# Generated by Django 5.1.3 on 2025-01-06 07:28

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ingredients',
            field=models.TextField(verbose_name='Інгредієнти'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.article_image_upload_to, verbose_name='Фотографія рецепту'),
        ),
    ]
