# Generated by Django 5.1.3 on 2025-01-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_article_description_alter_article_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепти'},
        ),
    ]
