# Generated by Django 5.1.3 on 2025-01-10 12:57

import django.db.models.deletion
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_article_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Опис кроку')),
                ('image', models.ImageField(null=True, upload_to=recipes.models.step_image_upload_to, verbose_name='Зображення кроку')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.article')),
            ],
        ),
    ]
