# Generated by Django 5.1.3 on 2025-01-10 13:21

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.step_image_upload_to, verbose_name='Зображення кроку'),
        ),
    ]
