# Generated by Django 5.1.3 on 2025-01-15 14:57

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='notes',
            field=models.TextField(null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to=recipes.models.article_image_upload_to, verbose_name='Фотографія рецепту'),
        ),
    ]
